rules:
  - id: account-age-min
    enabled: true
    minAccountAgeDays: 730
  - id: user-public-repos-min
    enabled: true
    minPublicRepos: 3
  - id: pr-total-changes-min
    enabled: true
    minTotalChanges: 500
  - id: block-protected-paths
    enabled: true
    blockedPaths:
      - .github/workflows/**
